### ISSUE TITLE
 Can't get Application Name using Deploy with CodeDeploy task after 1.8.0 extension upgrade

### ISSUE THREAD

**Issue by Yanal-Yves** [aws/aws-toolkit-azure-devops#373]
**Describe the bug**

In Azure devops pipeline build, we've had a working build step to deploy to AWS Codedeploy but now the step is failing with Can't find Application, which is the application defined in AWS Codedeploy. This was working version 1.7.0 version of the extension.

**To reproduce**

 Add the AWS tools extension to an azure devops build and add the Deploy With CodeDeploy step, then fill out all of the fields.

**Expected behavior**

This should run correctly

**Screenshots**

With 1.8.0
![image](https://user-images.githubusercontent.com/1196669/93646226-1d819200-fa06-11ea-8f57-81b4868874ab.png)

With 1.7.0
![image](https://user-images.githubusercontent.com/1196669/93646239-21adaf80-fa06-11ea-9531-8f24358a932c.png)

**Your Environment**

-   On-prem or cloud based?: Cloud based
-   Azure DevOps version: ?
-   AWS Toolkit for Azure DevOps version: 1.8.0

**Additional context**

**Comment by hunterwerlla** [comment]
The 1.8.0 CodeDeploy task is also working on our instance of Azure Devops, and none of this task's code has changed in the 1.8.0 release. Since it is getting this far and failing, there is probably an issue with your credentials or the name of the application. Are any other tasks having issues?

As a side note, this is where it is actually throwing, but we unfortunately do not log the error: https://github.com/aws/aws-toolkit-azure-devops/blob/master/Tasks/CodeDeployDeployApplication/TaskOperations.ts#L66

**Comment by Yanal-Yves** [comment]
Thank you for your message.

I have recreated the service connection (https://dev.azure.com/<organization>/<project>/_settings/adminservices) and now everything is working fine again. 

I forgot to mention that since the last successful build with 1.7.0, I have rotated the access key and I have updated the access key and secret in the service connection but the code deploy task didn't work until I created a new the service collection and updated the task configuration with the new service connection.
