### ISSUE TITLE
AWS Toolkit uses Node 6 execution handler, which will be deprecated soon.

### ISSUE THREAD

**Issue by monken** [aws/aws-toolkit-azure-devops#437]
**Describe the bug**

Any pipeline using this toolkit will now print:
```
[warning]This task uses Node 6 execution handler, which will be deprecated soon.
```

**To reproduce**

Run any pipeline using one of the commands in this toolkit

**Your Environment**

-   cloud based
-   Azure DevOps

**Additional context**

https://aka.ms/migrateTaskNode10

**Comment by bryceitoc9** [comment]
Hi @monken 

This has been something we've been looking into; we've been holding off on the migration for some time now due to the fact that Microsoft seemed to still be supporting Node6 fully, and that self-hosted users can continue using Node6 agents. However, [this issue](https://github.com/microsoft/azure-pipelines-tasks/issues/15493) finally seems like Microsoft is pushing the issue and let us migrate without leaving users in the dust. Thanks for the heads-up!

**Comment by GrayMatterConsulting** [comment]
Please update!  I'd be in a rough spot if the deprecation happens before it's updated.  Save me from having to roll my own and a few late nights!!!

**Comment by jsbUSMC** [comment]
@bryceitoc9 Thanks for letting us know that you have a fix in the works. Is there a timeframe you could provide when this will be deployed?

**Comment by MatiasGadeberg** [comment]
I also have a LOT of pipelines utilizing the toolkit and would be interested in knowing a timeframe for deployment :)

**Comment by gjerokrsteski** [comment]
It's similar in my company. We use the task in many pipelines and are very happy if you provide an upgrade to Node10 - Best regards, Gjero

**Comment by strout** [comment]
For anybody just waiting, you can set a pipeline variable `DISABLE_NODE6_DEPRECATION_WARNING=true` to suppress the warnings. (Found on the node 10 migration page.)

**Comment by bryceitoc9** [comment]
Hi all,

Still looking into this. The mechanical changes should be easy but we're making sure we know how to handle the cases of users who are on self-hosted legacy agents exclusively and are automatically updating their toolkit, since I'm fairly certain that this move will break them (we can't restrict installation to specific versions of Azure DevOps/TFS because the pipeline agents are separate and not known by our code until runtime). Checking with Microsoft in their related issue here: https://github.com/microsoft/azure-pipelines-tasks/issues/15493#issuecomment-982059189 .

We don't have a specific timeline for the move but we should have a decision made and a release out prior to Microsoft's deprecation at the end of March 2022.

**Comment by ssala7** [comment]
Can we have an update on this 
we are using this task: AmazonWebServices.aws-vsts-tools.ECRPushImage.ECRPushImage@1
and we are seeing an warning message:
##[warning]This task uses Node 6 execution handler, which will be removed March 31st 2022. If you are the developer of the task - please consider the migration guideline to Node 10 handler - https://aka.ms/migrateTaskNode10 (check this page also if you would like to disable Node 6 deprecation warnings). If you are the user - feel free to reach out to the owners of this task to proceed on migration.

**Comment by ajfis** [comment]
Hi Team,

Are we looking to have this out sometime soon?
We really need this update, if not do we have a way to work around this problem?

Kind regards,

**Comment by bryceitoc9** [comment]
We are still planning on releasing this before the deadline. We are attempting to ensure users who are on Azure Pipelines Agents that cannot support Node10 will be minimally affected.

**Comment by bryceitoc9** [comment]
FYI: We are looking to release 1.13.0 with Node10 support on **March 30, 2022**, one day before the deadline to give users who are self-hosting Node6 agents time to update. Please use https://github.com/aws/aws-toolkit-azure-devops/issues/453 if you have any questions!
